#!/bin/bash

check_command() {
    type $1 &> /dev/null || { echo "$1 not found." >&1; return 1; }
}

check_command expect || exit 127
check_command python || exit 127

if [ $# -eq 0 ]; then
    echo -e "provide services in SSH forwarding tunnel"
	echo -e "Usage:\n\t$0 [-i] <conf file> <vault file>"
    echo -e "Options:"
    echo -e "\t-i        show config info and exit."
	exit 0
fi

onlyshow=
while getopts ":i" opt; do
    case $opt in
      i ) onlyshow="-i"
          ;;
      ? ) echo "error input"
          exit 1;;
    esac
done
shift $(($OPTIND - 1))

. functions
# test
get_vault_file $2 &> /dev/null || { echo "failed to get vault file: $1" >&1; exit 1; }

# vault file located in ~/.vault/
vault=$(basename $2)

exec /bin/bash connector $onlyshow $1 $vault &

